### ISSUE TITLE
When adding in a third question to the questionnaire creator the order of questions gets messed up

### ISSUE THREAD

**Issue by p0isonedpanda** [AnikaLegal/clerk#1]
Steps to recreate:

1. Add two questions and fill out their fields
2. Add a third question

The third question will now appear between the two initial questions.

**Comment by MattSegal** [comment]
This is now fixed - questions on the form builder are sorted by database ID [here](https://github.com/AnikaLegal/clerk/blob/master/app/frontend/src/components/script/details.js#L34)
